'use strict'
import * as fs from 'node:fs'
import * as levels from './Level.mjs';
const { readFile } = fs.promises

import { getTroupeRoot } from './troupeRoot.mjs'
import { mkLogger } from './logger.mjs'
const logger = mkLogger('lib')

const info = x => logger.info(x)
const debug = x => logger.debug(x)

const __libcache = {}

export async function loadLibsAsync(obj, rtObj) {
    let libs = obj.libs
    obj.libs = {}
    for (let n = 0; n < libs.length; n++) {
        let lib = libs[n].lib;
        let decl = libs[n].decl;

        const key = lib + "." + decl
        if (__libcache[key]) {
            debug('lib cache hit on: ' + key)
            obj.libs[key] = __libcache[key];
            continue
        }

        // 1. Find the file -- note that we load all the libs from a default
        //    location

        let filename = getTroupeRoot() + "/lib/out/" + lib + ".js"

        // 2. Load the file -- note that this is an asynchronous operation
        let input = await readFile(filename, 'utf8')

        // File read operation finished; we are now in the callbacak that has
        // been asynchronously called by the node runtime 

        // TODO: check for error! 2018-07-03: aa

        // 3. Create a JS class (function) from it
        let Lib: any = new Function('rt', input);

        // 4. We create a "new" instance of the resulting class

        let libinstance = new Lib(rtObj);


        // load dependent libraries??

        // libinstance.loadlibs (() => 
        await loadLibsAsync(libinstance, rtObj)

        // 5. Execute .export() function to obtain the table note - this is a
        //    regular JS function (generated by the compiler) that we just call
        //    here 

        rtObj.setLibloadMode(); // 2019-01-03: AA; Hack
        let table = libinstance.export({__dataLevel:levels.BOT}).val.toArray();
        rtObj.setNormalMode();  // 2019-01-03: AA; EOH

        // 6. Lookup in the resulting table

        for (let i = 0; i < table.length; i++) {
            let name = table[i].val[0].val;
            let libf = table[i].val[1].val
            if (name == decl) {
                // We store the resulting function in the object that was provided
                // to us as an argument
                obj.libs[key] = libf;
                __libcache[key] = libf;
                break;
            }
        }
    }

    // Datatype version-skew check (normalization.md §10). Enforced here, in the
    // single universal library-load path, but kept as a self-contained pass so
    // it is easy to locate and reason about independently of value linking.
    await checkConsumedDatatypes(obj, rtObj)
}

// Cache of a library's exported datatype group hashes, keyed by library name.
const __datatypeHashCache: Record<string, string[]> = {}

// Read the exported datatype group hashes a library embeds in its compiled
// artifact (this.__datatypeHashes, set by the compiler for library builds).
async function loadExportedDatatypeHashes(libname: string, rtObj): Promise<string[]> {
    if (__datatypeHashCache[libname]) return __datatypeHashCache[libname]
    let filename = getTroupeRoot() + "/lib/out/" + libname + ".js"
    let input = await readFile(filename, 'utf8')
    let Lib: any = new Function('rt', input)
    let libinstance = new Lib(rtObj)
    let hashes = libinstance.__datatypeHashes || []
    __datatypeHashCache[libname] = hashes
    return hashes
}

// Verify that every datatype group hash the artifact consumed at compile time
// is still among the loaded library's exported group hashes (membership, not
// equality: library extension is harmless, a changed consumed group is not).
async function checkConsumedDatatypes(obj, rtObj) {
    let consumed = obj.__consumedDatatypeHashes
    if (!consumed) return
    for (let libname of Object.keys(consumed)) {
        let exported = await loadExportedDatatypeHashes(libname, rtObj)
        for (let h of consumed[libname]) {
            if (!exported.includes(h)) {
                throw new Error(
                    "datatype version skew: library '" + libname + "' no longer exports a "
                    + "datatype group that was consumed at compile time (group hash " + h
                    + "). The importer was compiled against a different version of '" + libname
                    + "'; recompile it against the current library.")
            }
        }
    }
}
